config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "animals#index"
  resources :users, only: [:new, :create, :show]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :animals
  namespace :admin do
    resources :locations, only: [:index, :new, :create]
  end

  resources :sightings

  resources :kingdoms, only:  [:show, :index]
  resources :phylums, only:  [:show, :index]
  resources :classes, only:  [:show, :index], as: :taxonomical_classes
  resources :orders, only:  [:show, :index]
  resources :families, only:  [:show, :index]
  resources :genus, only:  [:show, :index]
  resources :species, only:  [:show, :index]
  # get '/animals', to: 'animals#index'
  # get '/animals/new', to: 'animals#new', as: "new_animal"
  # post '/animals', to: 'animals#create'
  # get '/animals/:id', to: 'animals#show', as: 'animal'
  # get '/animals/:id/edit', to: 'animals#edit', as: 'edit_animal'
  # patch '/animals/:id', to: 'animals#update'
  # delete '/animals/:id', to: 'animals#destroy'
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
  belongs_to :location
  belongs_to :user

  validates :sighting_time, presence: true

  def short_sighting_text
    if non_sighting
      "#{animal.name} was not sighted at #{location.name}"
    else
      "#{animal.name} was sighted at #{location.name}"
    end
  end

  def full_sighting_text
    if non_sighting
      "#{animal.name} was not sighted at #{location.name} at #{sighting_time.strftime("%H:%M")} on #{sighting_time.strftime("%B %d")} by #{user.name}"
    else
      "#{animal.name} was sighted at #{location.name} at #{sighting_time.strftime("%H:%M")} on #{sighting_time.strftime("%B %d")} by #{user.name}"
    end
    # <%= @sighting.animal.name %> was
    # <% if @sighting.non_sighting %>
    # <strong>not</strong>
    # <% end %>
    # spotted at <%= @sighting.location.name %>
    # at <%= @sighting.sighting_time.strftime("%H:%M") %> on <%= @sighting.sighting_time.strftime("%B %d") %>
    # by <%= @sighting.user.name %>
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :require_login, expect: [:show, :index]
  before_action :allow_only_creator, only: [:edit, :update, :destroy]

  def index
    @sightings = Sighting.all.order(sighting_time: :asc)
  end

  def new
    @sighting = current_user.sightings.new
    @animals = Animal.all.order(name: :asc)
    @locations = Location.all.order(name: :asc)
  end

  def create
    @sighting = current_user.sightings.new(sighting_params)
    if @sighting.save
      redirect_to @sighting
    else
      flash.now[:error] = @sighting.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @sighting = Sighting.find(params[:id])
    @animals = Animal.all.order(name: :asc)
    @locations = Location.all.order(name: :asc)
  end

  def update
    @sighting = Sighting.find(params[:id])
    if @sighting.update(sighting_params)
      redirect_to @sighting
    else
      flash.now[:error] = @sighting.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @sighting = Sighting.find(params[:id])
  end

  def destroy
    Sighting.find(params[:id]).destroy
    redirect_to sightings_path
  end

  private

  def sighting_params
    params.require(:sighting).permit(:animal_id, :location_id, :sighting_time, :non_sighting)
  end

  def require_login
    unless logged_in?
      flash[:authorization_error] = "You must log in to add a sighting"
      redirect_to login_path
    end
  end

  def allow_only_creator
    unless creator?(Sighting.find(params[:id]).user)
      flash[:authorization_error] = "You can't change something you didn't create..."
      redirect_to sightings_path
    end
  end
end

app/views/sightings/_form.html.erb
<div class="container well well-md">
<%= form_for(@sighting) do |f| %>
  <%= f.label :animal %>
  <%= f.collection_select :animal_id, @animals, :id, :name %><br />

  <%= f.label :location %>
  <%= f.collection_select :location_id, @locations, :id, :name %><br />

  <%= f.datetime_select :sighting_time %><br />

  <%= f.label :non_sighting, "Non-sighting?" %>
  <%= f.check_box :non_sighting %>
  <br />
  <br />
  <%= f.submit %>
<% end %>
</div>

app/views/sightings/edit.html.erb
<h1 class="text-center container well well-sm">Did You See Something Wrong?</h1>
<%= render partial: "form" %>

app/views/sightings/index.html.erb
<div class="container well well-sm text-center">
  <h1 class="">
    <u>Animal Sightings</u>
  </h1>
  <h3>There have been <%= @sightings.count %> sightings</h3>
</div>

<div class="container">
  <div class="row">
    <% @sightings.each do |sighting| %>
        <div class="container col col-md-4">
            <h3 class=" well well-sm text-center"><%= link_to sighting.short_sighting_text, sighting %></h3>
        </div>
    <% end %>
  </div>
  <h2 class="text-center well well-sm"><%= link_to "New Sighting", new_sighting_path %></h2>
</div>

app/views/sightings/new.html.erb
<h1 class="text-center container well well-sm">What did you see?!</h1>
<%= render partial: "form" %>

app/views/sightings/show.html.erb
<h1 class="text-center container well well-sm">Sighting!</h1>

<div class="container">
  <div class="well well-sm row">

      <div class="col col-md-8">
        <p class="lead">
          <%= @sighting.full_sighting_text %>
        </p>
        <br />
        <br />
        <h3><%= link_to "What the heck is that?", @sighting.animal %></h3>
      </div>
      <div class="col col-md-4">
        <% if @sighting.animal.image_path %>
          <div class="animal_image">
            <%= image_tag @sighting.animal.wiki_img_url %>
          </div>
        <% end %>
      </div>
  </div>
</div>

<div class="container well well-md">
  <div class="row">
    <h4 class="text-center col col-md-4"><%= link_to "Back to Sightings", sightings_path %></h4>
    <h4 class="text-center col col-md-4"><%= link_to "Edit Sighting", edit_sighting_path %></h4>
    <h4 class="text-center col col-md-4"><%= link_to "Delete Sighting", @sighting, method: :delete %></h4>
  </div>
</div>