config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "animals#index"
  resources :users, only: [:new, :create, :show]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :animals
  namespace :admin do
    resources :locations, only: [:index, :new, :create]
  end

  resources :sightings

  resources :kingdoms, only:  [:show, :index]
  resources :phylums, only:  [:show, :index]
  resources :classes, only:  [:show, :index], as: :taxonomical_classes
  resources :orders, only:  [:show, :index]
  resources :families, only:  [:show, :index]
  resources :genus, only:  [:show, :index]
  resources :species, only:  [:show, :index]
  # get '/animals', to: 'animals#index'
  # get '/animals/new', to: 'animals#new', as: "new_animal"
  # post '/animals', to: 'animals#create'
  # get '/animals/:id', to: 'animals#show', as: 'animal'
  # get '/animals/:id/edit', to: 'animals#edit', as: 'edit_animal'
  # patch '/animals/:id', to: 'animals#update'
  # delete '/animals/:id', to: 'animals#destroy'
end

app/views/shared/_animal_container.html.erb
<div class="container col col-md-4">
  <a href=<%= "#{animal_path(animal)}" %>>
    <div class="well well-md">
      <div class="index_image">
        <%= image_tag animal.wiki_img_url, class: "center-block" %>
      </div>
      <h3 class="text-center"><%= link_to animal.name, animal %></h3>
    </div>
  </a>
</div>

app/views/shared/_animals_by_taxonomical_level.html.erb
<div class="container">
  <div class="row">
    <% data.animals.each do |animal| %>
      <%= render partial: "shared/animal_container", locals: {animal: animal} %>
    <% end %>
  </div>
</div>

app/views/shared/_tax_index.html.erb
<div class="container">
  <div class="row">

    <% levels.each do |level| %>
      <% if level.name %>
        <div class="container col col-md-4">
          <div class="well well-md">
            <h3>
                <%= link_to level.name, level %>
            </h3>
          </div>
        </div>
      <% end %>
    <% end %>

  </div>
</div>