config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "animals#index"
  resources :users, only: [:new, :create, :show]

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"

  resources :animals
  namespace :admin do
    resources :locations, only: [:index, :new, :create]
  end

  resources :sightings

  resources :kingdoms, only:  [:show, :index]
  resources :phylums, only:  [:show, :index]
  resources :classes, only:  [:show, :index], as: :taxonomical_classes
  resources :orders, only:  [:show, :index]
  resources :families, only:  [:show, :index]
  resources :genus, only:  [:show, :index]
  resources :species, only:  [:show, :index]
  # get '/animals', to: 'animals#index'
  # get '/animals/new', to: 'animals#new', as: "new_animal"
  # post '/animals', to: 'animals#create'
  # get '/animals/:id', to: 'animals#show', as: 'animal'
  # get '/animals/:id/edit', to: 'animals#edit', as: 'edit_animal'
  # patch '/animals/:id', to: 'animals#update'
  # delete '/animals/:id', to: 'animals#destroy'
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :legs, presence: true

  has_many :sightings

  belongs_to :kingdom, optional: true
  belongs_to :phylum, optional: true
  belongs_to :taxonomical_class, optional: true
  belongs_to :order, optional: true
  belongs_to :family, optional: true
  belongs_to :genus, optional: true
  belongs_to :species, optional: true

  def self.alpha_sorted
    all.order(name: :asc)
  end

  def no_taxonomical_data?
    !kingdom || !phylum || !taxonomical_class || !order || !family || !genus || !species
  end

  def add_taxonomical_data
    tax_data = WikiParser.get_taxonomical_data(name)

    kingdom = Kingdom.find_or_create_by(name: tax_data["Kingdom"])
    phylum = Phylum.find_or_create_by(name: tax_data["Phylum"])
    taxonomical_class = TaxonomicalClass.find_or_create_by(name: tax_data["Class"])
    order = Order.find_or_create_by(name: tax_data["Order"])
    family = Family.find_or_create_by(name: tax_data["Family"])
    genus = Genus.find_or_create_by(name: tax_data["Genus"])
    species = Species.find_or_create_by(name: tax_data["Species"])

    update(kingdom: kingdom,
           phylum: phylum,
           taxonomical_class: taxonomical_class,
           order: order,
           family: family,
           genus: genus,
           species: species)
  end

  def wiki_img_url
    "https://#{image_path}"
  end

  def sighting_number
    sightings.where(non_sighting: false).count
  end

  def non_sighting_number
    sightings.where(non_sighting: true).count
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :allow_only_admins, only: [:destroy]

  def index
    @animal = Animal.alpha_sorted
  end

  def show
    @animal = Animal.find(params[:id])
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      flash[:notice] = "Animal Created!"
      add_taxonomical_data(@animal)
      redirect_to @animal
    else
      flash.now[:error] = @animal.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
  end

  def update
    @animal = Animal.find(params[:id])
    @animal.update(animal_params)
    if @animal.no_taxonomical_data?
      add_taxonomical_data(@animal)
    end
    redirect_to @animal
  end

  def destroy
    @animal = Animal.find(params[:id])
    @animal.destroy
    redirect_to animals_path
  end

  private

  def animal_params
    params.require(:animal).permit(:name, :legs, :poisonous, :warm_blooded, :image_path)
  end

  def require_login
    unless logged_in?
      flash[:authorization_error] = "You must log in to add an animal"
      redirect_to login_path
    end
  end

  def allow_only_admins
    unless current_admin?
      flash[:authorization_error] = "You aren't authorized to destroy animals, you monster..."
      redirect_to animals_path
    end
  end

  def add_taxonomical_data(animal)
    animal.add_taxonomical_data
    if animal.image_path.strip == ""
      animal_pic = WikiParser.get_wiki_picture(animal.name)
      animal.update(image_path: animal_pic)
    end
  end
end

app/views/animals/_form.html.erb
<div class="container well well-md">
  <%= form_for(@animal) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %> <br/>
      <%= f.label :legs %>
      <%= f.text_field :legs %> <br/>
      <%= f.label :poisonous %>
      <%= f.check_box :poisonous %> <br/>
      <%= f.label :warm_blooded %>
      <%= f.check_box :warm_blooded %> <br/>
      <%= f.label :image_path %> <br/>
      <%= f.text_field :image_path %> - If blank will use Wikipedia image
      <br />
      <br />
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/animals/edit.html.erb
<h2 class="container well well-sm text-center">Edit an Animal!</h2>
<%= render partial: "form" %>

app/views/animals/index.html.erb
<h1 class="text-center container well well-sm"><u>Animals that may or may not be in the Turing Basement</u></h1>

<div class="container">
  <div class="row">
    <% @animal.each do |animal| %>
      <%= render partial: "shared/animal_container", locals: {animal: animal} %>
    <% end %>
  </div>
  <br />
  <!-- <p class="text-center">
    There are <%#= @animal.count %> animals
  </p> -->
  <h2 class="text-center well well-sm"><%= link_to "Add an Animal", new_animal_path %></h2>
</div>

app/views/animals/new.html.erb
<h2 class="container well well-sm text-center">Create a New Animal!</h2>
<%= render partial: "form" %>

app/views/animals/show.html.erb
<h1 class="text-center container well well-sm"><u><%= @animal.name %></u></h1>

<div class="container jumbotron">
  <div class="row">
    <div class="col col-md-4">
      <h3><u>Basic Info:</u></h3>
      <p>
        <strong>Legs:</strong> <%= @animal.legs %>
      </p>

      <p>
        <strong>Poisonous:</strong> <%= @animal.poisonous %>
      </p>

      <p>
        <strong>Warm Blooded:</strong> <%= @animal.warm_blooded %>
      </p>

      <p>
        <strong>Sightings:</strong> <%= @animal.sighting_number %>
      </p>

      <p>
        <strong>Non-Sightings:</strong> <%= @animal.non_sighting_number %>
      </p>
    </div>
    <div class="col col-md-4">
      <h3><u>Taxonomical Info:</u></h3>
      <h4><%= link_to "Kingdom:", kingdoms_path %> <%= link_to @animal.kingdom.name, @animal.kingdom if @animal.kingdom_id && @animal.kingdom.name %></h3>
      <h4><%= link_to "Phylum:", phylums_path %> <%= link_to @animal.phylum.name, @animal.phylum if @animal.phylum_id && @animal.phylum.name %></h4>
      <h4><%= link_to "Class:", taxonomical_classes_path %> <%= link_to @animal.taxonomical_class.name, @animal.taxonomical_class if @animal.taxonomical_class_id && @animal.taxonomical_class.name %></h4>
      <h4><%= link_to "Order:", orders_path %> <%= link_to @animal.order.name, @animal.order if @animal.order_id && @animal.order.name %></h4>
      <h4><%= link_to "Family:", families_path %> <%= link_to @animal.family.name, @animal.family if @animal.family_id && @animal.family.name %></h4>
      <h4><%= link_to "Genus:", genus_path %> <%= link_to @animal.genus.name, @animal.genus if @animal.genus_id && @animal.genus.name %></h4>
      <h4><%= link_to "Species:", species_index_path %> <%= link_to @animal.species.name, @animal.species if @animal.species_id && @animal.species.name %></h4>
    </div>
    <div class="col col-md-4">
      <h3><u>Picture:</u></h3>
      <% if @animal.image_path %>
        <div class="animal_image">
          <%= image_tag @animal.wiki_img_url %><br />
        </div>
      <% end %>
    </div>
  </div>

</div>
<div class="container well well-md">
  <div class="row">
    <h4 class="text-center col col-md-4"><%= link_to "Back to Animals", animals_path %></h4>
    <h4 class="text-center col col-md-4"><%= link_to "Edit Animal", edit_animal_path %></h4>
    <h4 class="text-center col col-md-4"><%= link_to "Delete Animal", @animal, method: :delete %></h4>
  </div>
</div>